version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db_mysql:
    container_name: qualix_db_mysql
    restart: unless-stopped
    image: mysql:latest
    tty: true
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=qualix_db
      - MYSQL_USER=qualix_db
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
volumes:
  mysql-data:
    external:
      name: qualix_db_mysql